/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package Master;

import java.awt.Color;

/**
 *
 * @author deepa
 */
public class SubGrpMasterPanel extends javax.swing.JPanel {

    /**
     * Creates new form SubGrpMasterPanel
     */
    public SubGrpMasterPanel() {
        initComponents();
        setSize(965,542);
        setBackground(Color.PINK);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();

        setLayout(null);

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        add(jScrollPane1);
        jScrollPane1.setBounds(0, 0, 960, 396);

        jButton1.setText("BACK");
        add(jButton1);
        jButton1.setBounds(770, 430, 176, 78);

        jButton2.setText("ADD");
        add(jButton2);
        jButton2.setBounds(0, 430, 176, 78);

        jButton3.setText("DELETE");
        add(jButton3);
        jButton3.setBounds(190, 430, 176, 78);

        jButton4.setText("MODIFY");
        add(jButton4);
        jButton4.setBounds(380, 430, 176, 78);

        jButton5.setText("VIEW");
        add(jButton5);
        jButton5.setBounds(570, 430, 176, 78);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
}
